"""
Application constants including default password, platform domains, and adult content domains.
"""

# Default main application password
DEFAULT_PASSWORD = "OpentheBlocker"

# Platform domains mapping
PLATFORM_DOMAINS = {
    "facebook": [
        "facebook.com",
        "www.facebook.com",
        "m.facebook.com",
        "mobile.facebook.com",
        "web.facebook.com",
    ],
    "instagram": [
        "instagram.com",
        "www.instagram.com",
        "m.instagram.com",
    ],
    "linkedin": [
        "linkedin.com",
        "www.linkedin.com",
        "mobile.linkedin.com",
    ],
    "twitter": [
        "twitter.com",
        "www.twitter.com",
        "mobile.twitter.com",
        "x.com",
        "www.x.com",
        "mobile.x.com",
    ],
    "youtube": [
        "youtube.com",
        "www.youtube.com",
        "m.youtube.com",
        "youtu.be",
    ],
    "tiktok": [
        "tiktok.com",
        "www.tiktok.com",
        "m.tiktok.com",
    ],
    "reddit": [
        "reddit.com",
        "www.reddit.com",
        "m.reddit.com",
        "old.reddit.com",
    ],
    "snapchat": [
        "snapchat.com",
        "www.snapchat.com",
    ],
}

# Casino/Gambling platform domains (comprehensive list)
CASINO_GAMBLING_DOMAINS = [
    # Major international casinos
    "1xbet.com",
    "www.1xbet.com",
    "1xbet.org",
    "www.1xbet.org",
    "bet365.com",
    "www.bet365.com",
    "betway.com",
    "www.betway.com",
    "betway.africa",
    "www.betway.africa",
    "22bet.com",
    "www.22bet.com",
    "22bet.africa",
    "www.22bet.africa",
    "dkwin.com",
    "www.dkwin.com",
    "dkwin.net",
    "www.dkwin.net",
    "hazze.com",
    "www.hazze.com",
    "hazze.net",
    "www.hazze.com",
    "www.hazze.net",
    "hgzy.app",
    "www.hgzy.app",
    "hgzygame.co",
    "www.hgzygame.co",
    "dkwin.com",
    "www.dkwin.com",
    "dkwin.net",
    "www.dkwin.net",
    "dkwin0.com",
    "www.dkwin0.com",
    "dkwin0.net",
    "www.dkwin0.net",
    "dkwinn.com",
    "www.dkwinn.com",
    "dkwinn.net",
    "www.dkwinn.net",
    "dkwinn.app",
    "www.dkwinn.app",
    "dkwin-game.com",
    "www.dkwin-game.com",
    "dkwin1.com",
    "www.dkwin1.com",
    "dkwin2.com",
    "www.dkwin2.com",
    "dkwin3.com",
    "www.dkwin3.com",
    "fbbazee.com",
    "www.fbbazee.com",
    "fbbazee.net",
    "www.fbbazee.net",
    # Popular online casinos
    "betmgm.com",
    "www.betmgm.com",
    "fanduel.com",
    "www.fanduel.com",
    "draftkings.com",
    "www.draftkings.com",
    "caesars.com",
    "www.caesars.com",
    "bovada.lv",
    "www.bovada.lv",
    "ignitioncasino.eu",
    "www.ignitioncasino.eu",
    "cafe.com",
    "www.cafe.com",
    "888casino.com",
    "www.888casino.com",
    "888sport.com",
    "www.888sport.com",
    "casino.com",
    "www.casino.com",
    "pokerstars.com",
    "www.pokerstars.com",
    "pokerstars.net",
    "www.pokerstars.net",
    "betvictor.com",
    "www.betvictor.com",
    "unibet.com",
    "www.unibet.com",
    "ladbrokes.com",
    "www.ladbrokes.com",
    "coral.co.uk",
    "www.coral.co.uk",
    "williamhill.com",
    "www.williamhill.com",
    "paddypower.com",
    "www.paddypower.com",
    "betfair.com",
    "www.betfair.com",
    "bwin.com",
    "www.bwin.com",
    "10bet.com",
    "www.10bet.com",
    "betfred.com",
    "www.betfred.com",
    "betsson.com",
    "www.betsson.com",
    "betway.co.za",
    "www.betway.co.za",
    "supabets.co.za",
    "www.supabets.co.za",
    "sportingbet.com",
    "www.sportingbet.com",
    "marathonbet.com",
    "www.marathonbet.com",
    "dafabet.com",
    "www.dafabet.com",
    "comeon.com",
    "www.comeon.com",
    "leovegas.com",
    "www.leovegas.com",
    "mrgreen.com",
    "www.mrgreen.com",
    "grosvenorcasinos.com",
    "www.grosvenorcasinos.com",
    "casumo.com",
    "www.casumo.com",
    "bet-at-home.com",
    "www.bet-at-home.com",
    "novibet.com",
    "www.novibet.com",
    "stake.com",
    "www.stake.com",
    "rolletto.com",
    "www.rolletto.com",
    "metaspins.com",
    "www.metaspins.com",
    "cryptobets.com",
    "www.cryptobets.com",
    # Sports betting platforms
    "fanduel.com",
    "www.fanduel.com",
    "pointsbet.com",
    "www.pointsbet.com",
    "ballybet.com",
    "www.ballybet.com",
    "barstoolsportsbook.com",
    "www.barstoolsportsbook.com",
    "betrivers.com",
    "www.betrivers.com",
    "foxbet.com",
    "www.foxbet.com",
    "twinspires.com",
    "www.twinspires.com",
    "wynnbet.com",
    "www.wynnbet.com",
]

# Adult content domains (comprehensive list)
ADULT_CONTENT_DOMAINS = [
    # Major adult video sites
    "pornhub.com",
    "www.pornhub.com",
    "xvideos.com",
    "www.xvideos.com",
    "xnxx.com",
    "www.xnxx.com",
    "redtube.com",
    "www.redtube.com",
    "youporn.com",
    "www.youporn.com",
    "tube8.com",
    "www.tube8.com",
    "spankwire.com",
    "www.spankwire.com",
    "keezmovies.com",
    "www.keezmovies.com",
    "extremetube.com",
    "www.extremetube.com",
    "beeg.com",
    "www.beeg.com",
    "xhamster.com",
    "www.xhamster.com",
    "xhamsterlive.com",
    "www.xhamsterlive.com",
    "pornhubpremium.com",
    "www.pornhubpremium.com",
    "xvideos.red",
    "www.xvideos.red",
    "porn.com",
    "www.porn.com",
    "tube.com",
    "www.tube.com",
    "adultswim.com",
    "www.adultswim.com",
    "adulttime.com",
    "www.adulttime.com",
    "bangbros.com",
    "www.bangbros.com",
    "brazzers.com",
    "www.brazzers.com",
    "realitykings.com",
    "www.realitykings.com",
    "digitalplayground.com",
    "www.digitalplayground.com",
    "naughtyamerica.com",
    "www.naughtyamerica.com",
    "wicked.com",
    "www.wicked.com",
    "vivid.com",
    "www.vivid.com",
    # Live cam sites
    "chaturbate.com",
    "www.chaturbate.com",
    "livejasmin.com",
    "www.livejasmin.com",
    "stripchat.com",
    "www.stripchat.com",
    "myfreecams.com",
    "www.myfreecams.com",
    "cam4.com",
    "www.cam4.com",
    "bongacams.com",
    "www.bongacams.com",
    "camsoda.com",
    "www.camsoda.com",
    "streamate.com",
    "www.streamate.com",
    "imlive.com",
    "www.imlive.com",
    "livejasmine.com",
    "www.livejasmine.com",
    "xhamsterlive.com",
    "www.xhamsterlive.com",
    # Subscription/adult content platforms
    "onlyfans.com",
    "www.onlyfans.com",
    "justforfans.com",
    "www.justforfans.com",
    "manyvids.com",
    "www.manyvids.com",
    "avnstars.com",
    "www.avnstars.com",
    "fansly.com",
    "www.fansly.com",
    "pornhubmodelhub.com",
    "www.pornhubmodelhub.com",
    # Adult dating/hookup sites
    "ashleymadison.com",
    "www.ashleymadison.com",
    "adultfriendfinder.com",
    "www.adultfriendfinder.com",
    "fetlife.com",
    "www.fetlife.com",
    # Other adult sites
    "xvideos2.com",
    "www.xvideos2.com",
    "xvideos3.com",
    "www.xvideos3.com",
    "pornmd.com",
    "www.pornmd.com",
    "thumbzilla.com",
    "www.thumbzilla.com",
    "youjizz.com",
    "www.youjizz.com",
    "sunporno.com",
    "www.sunporno.com",
    "4tube.com",
    "www.4tube.com",
]

# Windows hosts file path
HOSTS_FILE_PATH = r"C:\Windows\System32\drivers\etc\hosts"
HOSTS_BACKUP_PATH = "backup_hosts"
REDIRECT_IP = "127.0.0.1"

# App metadata
APP_NAME = "DeepFocus"
APP_VERSION = "0.1.0"
CREATOR_NAME = "Sifat"

# Settings file path
SETTINGS_FILE = "settings.json"
